apiVersion: v1  # ✅ Defines this as a ConfigMap
kind: ConfigMap
metadata:
  name: prom-config
  namespace: monitoring
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s  # ✅ Defines how often Prometheus collects metrics
      evaluation_interval: 30s  # ✅ Rule evaluation interval
    scrape_configs:
      - job_name: "mywebapp"
        static_configs:
          - targets: ["mywebapp-service.default.svc.cluster.local:80"]
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]  # ✅ Ensures Prometheus self-monitors
    rule_files:
      - "alertrule.yaml"

