---
# MyApp Service Exposure
# This YAML file defines a Kubernetes service for MyApp, which is part of the application deployment.
# It specifies the service type, selector, and ports for MyApp.
  
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - name: http
      port: 80
      targetPort: 80  # ✅ Matches containerPort in Deployment
      nodePort: 30001  # ✅ Explicitly defined NodePort for external access

