
---
# 4️⃣ ArgoCD Application Configuration
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myargocdapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/Oreire/kube-argo-cd.git"  # ✅ Ensure this is the correct repo
    path: deploy
    targetRevision: "main"
  destination:
    namespace: default  # ✅ Matches MyApp deployment
    server: "https://127.0.0.1:63010"  # ✅ Verify Kubernetes API URL
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  # ✅ Automatically create namespace if it doesn't exist