apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: default
  labels:
    app: myapp
    app.kubernetes.io/instance: myapp
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: myapp
    app.kubernetes.io/version: "1.0.0"
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: "Prune=true"
spec:
  project: default
  source:
    repoURL: "https://github.com/YourRepo/kubernetes-config.git"
    path: "deploy"
    targetRevision: "main"
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

