
# ArgoCD Namespace Manifest
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
namespace: argocd

