# Expose ArgoCD server via NodePort
# This configuration exposes the ArgoCD server on a NodePort for external access.

apiVersion: v1
kind: Service
metadata:
  name: argocd-service
  labels:
    app: argocd-server
  namespace: argocd
spec:
  selector:
    app: argocd-server
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 443
      nodePort: 30003  # ✅ Accessible via http://localhost:30003



