# Expose ArgoCD server via NodePort
# This configuration exposes the ArgoCD server on a NodePort for external access.
apiVersion: v1
kind: Service
metadata:
  name: argocd-service
  namespace: argocd
spec:
  selector:
    app: argocd-server
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 443
      nodePort: 31080 # ✅ Ensured valid NodePort for ArgoCD server


