# This YAML file contains the configuration for deploying ArgoCD Service on a Kubernetes cluster.

apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  selector:
    app: argocd-server
  type: NodePort
  ports:
    - Name: argocd-ui  # ✅ Name for the UI port
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30006
      
    - name: argocd-metrics  # ✅ Name for the metrics port
      protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 30008



