# This YAML file contains the configuration for deploying ArgoCD Service on a Kubernetes cluster.

apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  type: NodePort
  selector:
    app: argocd-server
  ports:
    - nodePort: 30006
      port: 8080
      protocol: TCP
      targetPort: 8080
    - nodePort: 30008
      port: 8083
      protocol: TCP
      targetPort: 8083





