apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: argocd
  labels:
    app: argocd-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-server
  template:
    metadata:
      labels:
        app: argocd-server
    spec:
      containers:
        - name: argocd-server
          image: bitnami/argo-cd@sha256:f71bd94f4930cb12dea1d8bf158a3dd1231d395bb9ece998dbda3e577f6e1c04
          ports:
            - containerPort: 443
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "750m"
              memory: "768Mi"
          livenessProbe:
            httpGet:
              path: "/healthz"
              port: 443
              host: "localhost"
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: "/healthz"
              port: 443
              host: "localhost"
            initialDelaySeconds: 10
            periodSeconds: 5
          env:
            - name: ARGOCD_SERVER
              value: "argocd-server"