apiVersion: v1  # ✅ Ensures correct API version for ConfigMap
kind: ConfigMap  # ✅ Defines this as a Kubernetes ConfigMap
metadata:
  name: prom-config
  namespace: monitoring
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 30s
    scrape_configs:
      - job_name: "mywebapp"
        static_configs:
          - targets: ["mywebapp-service.default.svc.cluster.local:80"]
    # rule_files:
    #   - "alerting-rules.yaml"

