apiVersion: v1  # ✅ Ensures correct API version for ConfigMap
kind: ConfigMap  # ✅ Defines this as a Kubernetes ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prom-config.yaml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 30s
    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["mywebapp-service.default.svc.cluster.local:80"]
      
