scrape_configs:
  - job_name: "mywebapp"  # ✅ Updated to match your web application
    static_configs:
      - targets: ["mywebapp-service.default.svc.cluster.local:80"]  # ✅ Ensure the correct service name

