name: Deploy ArgoCD & MyApp with Port Forwarding

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, Windows, X64]  # Runs on your local machine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize Terraform Configuration
        run: |
          cd infra
          terraform init
          echo "Initializing Terraform configuration..."
                
      - name: Validate Terraform Configurations
        run: |
          cd infra
          terraform validate
          echo "Validating Terraform configuration..."
      
      - name: Format Terraform Configurations
        run: |
          cd infra
          terraform fmt 
          echo "Checking Terraform format..."
      
      - name: Plan Terraform Changes
        run: |
          cd infra
          terraform plan -out=ArgoCD-Plan
          echo "Planning Terraform changes..."

      - name: Apply Terraform Configuration
        run: |
         cd infra
         terraform apply -auto-approve
          #terraform destroy -auto-approve

      - name: Verify Kubernetes Deployments
        run: |
          kubectl get pods -n argocd
          kubectl get services -n argocd
          kubectl get pods -n default
          kubectl get services -n default

      - name: Port Forward ArgoCD Server
        run: |
          kubectl port-forward svc/argocd-server 8080:443 -n argocd &
      
      - name: Port Forward MyApp Service
        run: |
          kubectl port-forward svc/myapp-service 8081:80 -n default &
      - name: Wait for Port Forwarding
        run: |
          sleep 10  # Wait for port forwarding to establish
      - name: Access ArgoCD UI
        run: |
          echo "Access ArgoCD UI at http://localhost:8080"
          echo "Access MyApp at http://localhost:8081"
      - name: Cleanup
        run: |
          # Optionally, you can add cleanup steps here
          echo "Cleanup steps can be added here if needed."
