name: Deploy ArgoCD & MyApp with Port Forwarding

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, Windows, X64]  # Runs on your local machine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Apply Terraform Configuration
        run: |
          cd infra
          terraform init
          terraform apply -auto-approve --refresh-only

      - name: Identify Failed Resources
        run: |
          terraform plan -detailed-exitcode
        continue-on-error: true

      - name: Recreate Failed Resources
        if: failure()
        run: |
          terraform taint kubernetes_deployment.argocd_server || true
          terraform taint kubernetes_service.myapp_service || true
          terraform apply -auto-approve

      - name: Verify Kubernetes Deployments
        run: |
          kubectl get pods -n argocd
          kubectl get services -n argocd
          kubectl get pods -n default
          kubectl get services -n default

      - name: Port Forward ArgoCD Server
        run: |
          kubectl port-forward svc/argocd-server 8080:443 -n argocd &
      
      - name: Port Forward MyApp Service
        run: |
          kubectl port-forward svc/myapp-service 8081:80 -n default &
      
      - name: Wait for Port Forwarding
        run: |
          sleep 10  # Wait for port forwarding to establish
      - name: Access ArgoCD UI
        run: |
          echo "Access ArgoCD UI at http://localhost:8080"
          echo "Access MyApp at http://localhost:8081"