name: Deploy ArgoCD & MyApp on Local Kubernetes (Docker Desktop)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, Windows, X64]  # Runs on your local machine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify Kubernetes Context
        run: |
          kubectl config current-context
          kubectl get nodes
          echo "Confirmed Kubernetes context is Docker Desktop."

      - name: Apply ArgoCD Service Manifest from Local File
        run: |
          cd deploy
          kubectl apply -f argoservice.yaml
          echo "ArgoCD server manifest applied successfully."

      - name: Apply ArgoCD Application Manifest on Local Cluster
        run: |
          cd deploy
          kubectl apply -f argoapp.yaml
          echo "ArgoCD installed successfully."

      - name: Apply MyApp Deployment Manifest on Local Cluster
        run: |
          cd deploy
          kubectl apply -f myapp.yaml
          echo "Application deployed successfully."
    
      - name: Apply MyApp Service Manifest
        run: |
          cd deploy 
          kubectl apply -f appservice.yaml
          echo "MyApp service manifest applied successfully."
      
      - name: Verify MyApp Deployment && Services
        run: |
          cd deploy
          kubectl get pods -n default
          kubectl get svc -n default
          echo "MyApp deployment verified."

      - name: Verify ArgoCD Application
        run: |
          cd deploy
          kubectl get applications -n argocd
          echo "ArgoCD application verified."

      - name: Verify ArgoCD Server
        run: |
          cd deploy
          kubectl get pods -n argocd
          kubectl get svc -n argocd
          echo "ArgoCD server and services verified."

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f deploy/monitoring/
          echo "Monitoring stack applied successfully."
    
      - name: Verify Monitoring Stacks
        run: |
          cd deploy/monitoring/
          kubectl get deploy -n monitoring
          kubectl get pods -n monitoring
          echo "Verifying Monitoring service stack."
          kubectl get svc -n monitoring
          echo "ALL MONITORING STACKS VERIFIED."
      
      - name: Start Port Forwarding for ArgoCD & MyApp
        run: |
          cd deploy
          nohup kubectl port-forward svc/argocd-server 30013:8080 -n argocd &
          nohup kubectl port-forward svc/myapp-service 30014:80 -n default &
          sleep 60
          echo "Local Port Forwarding Setup: ArgoCD on http://localhost:30013 | MyApp on http://localhost:30014"
      
      - name: Start Port Forwarding for Prometheus
        run: |
          nohup kubectl port-forward svc/prometheus-operated -n monitoring 9090:9090 > prometheus.log 2>&1 &
          sleep 60
          echo "Local Port Forwarding Setup: Prometheus on http://localhost:9090"
          
      - name: Start Port Forwarding for Grafana
        run: |
          nohup kubectl port-forward svc/grafana -n monitoring 3000:80 &
          sleep 60
          echo "Local Port Forwarding Setup: Grafana on http://localhost:3000"
      
      - name: Cleanup
        run: |
          cd deploy
          Get-Process | Where-Object { $_.ProcessName -match "kubectl" } | Stop-Process -Force
          echo "Port forwarding processes cleaned up."

