name: Deploy ArgoCD & MyApp on Local Kubernetes (Docker Desktop)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, Windows, X64]  # Runs on your local machine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify Kubernetes Context
        run: |
          kubectl config current-context
          kubectl get nodes
          echo "Confirmed Kubernetes context is Docker Desktop."

      - name: Apply ArgoCD Application Manifest on Local Cluster
        run: |
          cd deploy
          kubectl apply -f argoapp.yaml
          echo "ArgoCD installed successfully."

      - name: Apply MyApp Manifest on Local Cluster
        run: |
          cd deploy
          kubectl apply -f myapp.yaml
          echo "Application deployed successfully."

      - name: Wait for MyApp Deployment to Be Ready
        run: |
          kubectl rollout status deployment/mywebapp -n default --timeout=120s
          kubectl wait --for=condition=Ready pod -l app=mywebapp -n default --timeout=120s
          echo "MyApp deployment is ready."

      - name: Start Port Forwarding for ArgoCD & MyApp
        run: |
          cd deploy
          kubectl port-forward svc/argocd-service 30888:80 -n argocd &
          kubectl port-forward svc/myapp-service 30999:80 -n default &
          sleep 10
          echo "Local Port Forwarding Setup: ArgoCD on http://localhost:30888 | MyApp on http://localhost:30999"

      - name: Cleanup
        run: |
          cd deploy
          Get-Process | Where-Object { $_.ProcessName -match "kubectl" } | Stop-Process -Force
          echo "Port forwarding processes cleaned up."

